---
- name: 1 Rule
  hosts: all
  sources:
    - name: performance source
      performance:
        limit: 1
  rules:
    - name: a rule
      condition: text == "hello"
      action:
        argtest:
